name: Partie 1 - Decouverte GitHub Actions

on:
  push:
    branches:
      - main
      - test
      - test-cicd
  workflow_dispatch:

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say hello to me
        run: printf "Hello ${{ github.actor }} !"

      - name: List files in the repository
        # Le pipe (|) permet d'ecrire du texte multilignes
        run: |
          ls ${{ github.workspace }}

      - name: Ma commande Linux personnalisee
        run: |
          echo "Date et heure actuelle : $(date)"
